### ISSUE TITLE
Linux: Wal prevents session closing

### ISSUE THREAD

**Issue by atsib** [corporateshark/WCMCommander#418]
When closing a session in Linux/Debian with an opened Wal Commander, the behavior is:
(1) session is not closed
(2) there is something like an attempt to restore the session being closed, i.e. already closed windows are reopened

My system is Debian/semi-Jessie (Astra-Linux CE) kernel 3.16, fly-dm desktop manager
Wal is a very good idea!

**Comment by helgp** [comment]
This may be caused by library compatibility problem.

@atsib,

Could you, please, try the wcm binary at the link below, and share with us the result? 

http://divgrad.com/walcommander/wcm-0.19.1_gcc-4.7.2_libc.2.13

Put the binary aside (or in place of) the original /usr/bin/wcm, make it executable using "chmod +x FILENAME", start it, and see whether the problem still exist. This above binary is built with libraries that should match the Astra-Orel Linux.

**Comment by atsib** [comment]
Thank you for your attempt. Unfortunately the problem still exists. Moreover, your build shows one more: any attempt to move wcm window by mouse closes it.
Versions of my build:
gcc 4.9.1
libc 2.19

**Comment by corporateshark** [comment]
@atsib Does this mouse problem exist in other builds?

**Comment by helgp** [comment]
@atsib 

Could you provide more details on the environment, where the bug is observed? Link to bootable ISO file with distributive would suffice.

**Comment by atsib** [comment]
@corporateshark, this problem I see first time and only in the helgp build. My build has not it.

**Comment by atsib** [comment]
After updating AstraLinux to version 1.10.2 (kernel 3.16) the problem no longer exists. I think this issue may be closed. Thank you.
